// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7c007D81ntVuu6xk5DkjwphOuWmNLew',
    appId: '1:563040145590:web:9bdfecd22fb4d788821617',
    messagingSenderId: '563040145590',
    projectId: 'restoran-627f8',
    authDomain: 'restoran-627f8.firebaseapp.com',
    databaseURL: 'https://restoran-627f8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'restoran-627f8.appspot.com',
    measurementId: 'G-00MQBNX282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ77grwI2bJm4ZisXupL5EBRSwv5qtCJ0',
    appId: '1:563040145590:android:a42e05ceaaec053d821617',
    messagingSenderId: '563040145590',
    projectId: 'restoran-627f8',
    databaseURL: 'https://restoran-627f8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'restoran-627f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-lqc_396e-MsEIZ-do8hhYppQ171Az8',
    appId: '1:563040145590:ios:4ff9ae682ca83dca821617',
    messagingSenderId: '563040145590',
    projectId: 'restoran-627f8',
    databaseURL: 'https://restoran-627f8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'restoran-627f8.appspot.com',
    iosClientId: '563040145590-vgb49t1jphhc1bmdtsb8184bv3j81u8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-lqc_396e-MsEIZ-do8hhYppQ171Az8',
    appId: '1:563040145590:ios:4ff9ae682ca83dca821617',
    messagingSenderId: '563040145590',
    projectId: 'restoran-627f8',
    databaseURL: 'https://restoran-627f8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'restoran-627f8.appspot.com',
    iosClientId: '563040145590-vgb49t1jphhc1bmdtsb8184bv3j81u8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoranApp',
  );
}
